name: QA Basic Check

on:
  pull_request:
    branches:
      - main

jobs:
  qa-check:
    runs-on: ubuntu-latest

steps:
  - name: Paso QA exitoso
    run: echo "Primer paso OK"

  - name: Paso QA fallido intencional
    run: |
      echo "Simulando fallo QA"
      exit 1
